
```java
public class Main4 {
    public static void main(String[] args) {
        System.out.println("test 1");

        try {
            try {
                throw new Ex();
            }finally {
                System.out.println("抛出异常1次");
            }
        }catch (Ex ex){
            System.out.println("捕捉抛出的异常");
        }finally {
            System.out.println("抛出异常2次");
        }
    }
}

class Ex extends Exception{

}

```
